shop:
  products:
    SUGAR: 62.94
    WINE: 76.49
    PANCETTA: 71.23
    LEMONS: 43.98
    COOKIE: 68.61
    PASTA: 86.65
    BEANS: 89.34
    BANANAS: 47.9
    MILK: 55.49
    RICE: 84.0
    BEEF: 26.91
    FISH: 56.12
    MELON: 10.95
    COFFEE: 92.95
    MINTS: 46.16
    EGGPLANT: 34.32
    SAUCE: 50.57
    VINEGAR: 32
    CROISSANT: 109
  pathFile: c:\temp\cart_summary.json
logging:
  level:
    root: ERROR
